GET http://localhost:5000/users

###
GET http://localhost:5000/users/1


###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Fajar Putra",
    "email": "fajar270304@gmail.com",
    "gender": "Male"

}

###
PATCH http://localhost:5000/users/1
Content-Type: application/json

{
    "name": "Fajar Putra Herianto",
    "email": "fajarph.dev@gmail.com",
    "gender": "Male"

}


###
DELETE http://localhost:5000/users/2
